export type TimeBucket = "earlyMorning" | "morning" | "afternoon" | "evening" | "night" | "anytime";

export const PROMPT_CATALOG: Record<TimeBucket, readonly string[]> = {
  earlyMorning: [
    "Still half asleep? Grab your coffee and jot down whatever's on your mind.",
    "What's the one thing that actually needs to get done today?",
    "Got a quick thought before the morning gets crazy?",
    "Up early today. What's the first thing on your mind?",
    "Clean slate today. What are you tackling first?",
    "Any weird dreams or early thoughts to get down?",
    "How did you sleep? Ready for today, or need a minute?",
    "What's the main thing on your to-do list today?",
    "First cup of the day. How are you feeling?",
    "A quiet moment before the day takes off. What's on your mind?",
    "Got an early reminder for yourself? Write it down now.",
    "What's one thing you want to get out of the way today?",
    "Quiet room, fresh morning. What are you thinking about?",
    "Starting the day. What's the game plan?",
    "Any early ideas striking you before work starts?",
    "What would make today feel like a good day?",
    "Jot down your top three things before the messages start rolling in.",
    "Early start. What's got your attention today?",
    "Before you dive into tasks, take a breath. How's your head?",
    "What's one thing you don't want to forget to do today?",
    "The world is still pretty quiet. What's on your radar?",
    "Got a quick note to leave for future-you today?",
    "What's the first problem you're solving this morning?",
    "Take it slow this morning. What's the priority?",
    "Ready to roll, or still waking up? Note where your head's at.",
    "Any errands or chores to get done before work?",
    "What are you dreading or excited about today?",
    "Dump your early morning thoughts here and clear your mind.",
    "First thought that popped into your head today—what was it?",
    "What's the schedule looking like for today?",
    "A peaceful morning so far. What are you working toward?",
    "Got a little burst of early morning motivation? Jot it down.",
    "What's the most important task on your desk today?",
    "Take a second for yourself before opening your inbox.",
    "How's your mood heading into this morning?",
    "Write down the one thing you really can't procrastinate on today.",
    "Early coffee thoughts. Where are you headed today?",
    "What's something small you're looking forward to today?",
    "Jot down what you need to remember before the day picks up speed.",
    "Morning check-in. What's the focus?",
  ],
  morning: [
    "What are you working on right now?",
    "Deep in the weeds or making solid progress?",
    "Honestly, what's taking up most of your brain right now?",
    "Got a quick to-do or idea? Drop it here before you forget.",
    "How is the morning going so far? Busy or steady?",
    "Did you finish that first task yet, or got sidetracked?",
    "Save that random thought before jumping into your next meeting.",
    "What's the most annoying thing on your plate this morning?",
    "Quick brain dump: what's currently open in your head?",
    "Making things happen. What's next on your list?",
    "Take a 30-second breather. How are you feeling?",
    "Any quick wins or checked-off tasks so far today?",
    "Got an interesting idea while working? Jot it down here.",
    "What's keeping you focused (or distracted) this morning?",
    "Did someone say something today that made you think?",
    "How's your workspace vibe right now? Quiet or chaotic?",
    "Quick note: where did you just leave off?",
    "What's the main blocker you're trying to figure out?",
    "Write down that task before it slips out of your head.",
    "Are you in flow right now, or just powering through?",
    "Mid-morning check-in: what's the plan before lunch?",
    "Anything unexpected pop up this morning?",
    "How's your energy holding up so far?",
    "Take a second to write down whatever you just figured out.",
    "What's one thing you're glad you got done already?",
    "Coffee #2? What are you hammering out right now?",
    "Got a fast update on what you're building or fixing?",
    "Don't let that side-idea distract you—park it here.",
    "What's the biggest priority for the rest of this morning?",
    "Jot down any quick notes from your calls or chats.",
    "How's the to-do list looking halfway through the morning?",
    "Step away from the screen for a second. What's on your mind?",
    "What's a decision you just had to make?",
    "Feeling productive today, or is it one of those days?",
    "Write down your next step so you don't lose momentum.",
    "What's the most interesting thing that happened so far?",
    "Got a quick thought on your current project?",
    "Checking in. What needs your attention next?",
    "Drop a quick note to clear your head before the next task.",
    "How are things actually tracking this morning?",
  ],
  afternoon: [
    "How's your afternoon shaping up so far?",
    "Post-lunch slump hitting, or got your second wind?",
    "What's the main thing left on your plate for today?",
    "Quick midday brain dump. What's on your mind?",
    "Did lunch help reset things? What's next?",
    "Need to write something down before you forget it?",
    "What got done this morning, and what's the afternoon target?",
    "Take a minute to stretch. How's your head feeling?",
    "Any action items or follow-ups from recent chats?",
    "Afternoon grind. What are you powering through right now?",
    "What's one thing you really want to wrap up before tonight?",
    "Did you solve that problem from earlier, or still digging?",
    "Step back for a second. How is today actually turning out?",
    "Got a fresh idea during a break? Save it here.",
    "How's your energy level doing right now?",
    "Jot down a quick checkpoint: what's left on the to-do list?",
    "Any funny, strange, or memorable moments this afternoon?",
    "What are you working on before the workday winds down?",
    "Write down where you're stuck, or what you just fixed.",
    "The afternoon is flying by. What's taking your time?",
    "Need a quick mental reset? Put your thoughts down here.",
    "What's something you checked off that you're glad is done?",
    "Any quick notes or reminders for tomorrow already popping up?",
    "How are the afternoon meetings or tasks going?",
    "Take 10 seconds to log where you are right now.",
    "What's the most useful thing that happened today?",
    "Afternoon sunlight shifting. What are you up to?",
    "Don't let that thought slip away—jot it down now.",
    "Are you on track with what you wanted to do today?",
    "What's one thing you can cross off your list right now?",
    "Quick note on whatever you're building or researching.",
    "Feeling tired, wired, or somewhere in between?",
    "What's the headline of your day so far?",
    "Wrap up your current thought before you switch tasks.",
    "Any conversations from today that stood out?",
    "What's one task you've been putting off all day?",
    "How's your focus holding up this afternoon?",
    "Drop a quick note about what's going on around you.",
    "Almost at the finish line for today. What's next?",
    "Afternoon check-in. What's top of mind?",
  ],
  evening: [
    "Work is wrapping up. How did today actually go?",
    "Shutting down the laptop? What did you get done?",
    "Write down tomorrow's #1 task so you can relax tonight.",
    "Put your thoughts down here so you can stop thinking about work.",
    "What was the most exhausting or rewarding part of today?",
    "Any loose ends you need to remember for tomorrow morning?",
    "The day is winding down. What made you smile today?",
    "Did you finish what you wanted to finish today?",
    "How was the balance between work and life today?",
    "Time to switch off work mode. What's on your mind?",
    "What was the hardest thing you tackled today?",
    "A quick evening brain dump to clear your head.",
    "What did you have for dinner, or what are you making?",
    "Any good chats, walks, or moments this evening?",
    "What's one thing you're really glad you did today?",
    "Honest summary of today in one sentence—what would it be?",
    "Letting go of today's stress. What went right?",
    "Jot down anything you don't want to carry into tomorrow.",
    "How are you unwinding tonight?",
    "What was the highlight of your day?",
    "Ready to relax, or still got chores to knock out?",
    "Log a quick recap of your day before you forget the details.",
    "What's something you learned or noticed today?",
    "Evening calm. How does your head feel right now?",
    "Who did you spend time with or talk to today?",
    "Take a minute to give yourself credit for what you got done.",
    "What's on the agenda for tonight? Movies, books, or rest?",
    "Any creative ideas that came up after work hours?",
    "Drop today's thoughts into the timeline and sign off.",
    "What was something funny or weird that happened today?",
    "How was today compared to what you expected this morning?",
    "Write down any quick personal errands for tomorrow.",
    "Leaving today behind. What's the takeaway?",
    "What are you looking forward to tomorrow?",
    "A warm drink, a quiet evening. What's on your mind?",
    "Did you take any good photos today? What was the moment?",
    "Closing the books on today. How are you feeling?",
    "What was the best conversation you had today?",
    "Everything's done for the day. Take a breath.",
    "Evening check-in. Time to unwind.",
  ],
  night: [
    "Late night thoughts? Jot them down so you can get some sleep.",
    "Can't sleep? Write it down and get it out of your head.",
    "Offload whatever's spinning in your head before you rest.",
    "Midnight brain dump. What's keeping you awake?",
    "Got a late-night idea? Save it here so tomorrow-you finds it.",
    "The house is quiet now. What are you thinking about?",
    "Don't let tomorrow's to-do list keep you up. Write it down.",
    "How was today, honestly? Put it down in a few words.",
    "Late night stillness. Working late or just relaxing?",
    "A quick note before turning off the lights.",
    "What's a thought that made you smile today?",
    "Clear your mental tabs so you can sleep with a calm mind.",
    "Another day in the books. How are you feeling?",
    "Late night reflections. What stood out from today?",
    "Write down that lingering thought and let it go for the night.",
    "No more tasks today. What's the closing thought?",
    "What was the sweetest or calmest moment of your day?",
    "Under the quiet night sky. What's on your heart?",
    "Got a random realization in the dark? Note it down.",
    "Everything's saved. Time to unplug and rest.",
    "What's one thing you're grateful for before you sleep?",
    "Late night work session? Drop a quick note on where you stopped.",
    "A quiet midnight check-in with yourself.",
    "What's something you want to do differently tomorrow?",
    "Deep breaths into the quiet night. How's your head?",
    "Write down that crazy idea before you forget it in the morning.",
    "Closing out the day with an honest thought.",
    "Rest well tonight. What was today's win?",
    "A final note to wrap up today's timeline.",
    "What's playing in your headphones right now?",
    "The world is asleep. What's keeping you company?",
    "Don't overthink it—just write what you feel right now.",
    "Leaving today's worries right here on the page.",
    "What's the last thing on your mind before sleep?",
    "A peaceful close to an eventful day.",
    "Got a reminder for tomorrow morning? Jot it down now.",
    "Sleep is calling. What was today's highlight?",
    "Late night thoughts: raw, honest, unfiltered.",
    "Everything's written down. Time to rest your eyes.",
    "Signing off for the night. Sleep well.",
  ],
  anytime: [
    "Got a thought, task, or note? Drop it here.",
    "Honestly, what's on your mind right this second?",
    "Don't lose that thought—save a quick note.",
    "Quick brain dump: what are you trying to figure out?",
    "A quick update on whatever you're doing right now.",
    "Got a random idea? Dump it here before you lose it.",
    "What's the one thing you can't afford to forget?",
    "Take 10 seconds. What's happening around you?",
    "Record a quick voice note, snap a photo, or write a line.",
    "How are you feeling right now, in one sentence?",
    "What's a decision you had to make recently?",
    "A quick checkpoint in the middle of your day.",
    "Write down what's bothering you or exciting you.",
    "What are you listening to, watching, or reading right now?",
    "Drop a quick pin on this exact moment.",
    "What's something small that made you smile today?",
    "Jot down a quick note to untangle your head.",
    "What's an idea worth keeping for later?",
    "Got a quick to-do? Write it down before it slips.",
    "What's something you don't want to forget a year from now?",
    "Quick reality check: how is your energy right now?",
    "What's the vibe of where you're sitting right now?",
    "A quick note to your future self.",
    "What's something funny or weird someone said recently?",
    "Take a breath. What's actually important right now?",
    "Document a small win before moving on to the next thing.",
    "What's an interesting problem you're dealing with?",
    "Clear out your mental clutter with a quick note.",
    "Write a quick one-liner about today.",
    "What's currently taking up the most space in your head?",
    "A passing thought worth remembering.",
    "What made you pause or look up today?",
    "Record what you're working on before you switch tasks.",
    "What's a simple thing you're appreciating right now?",
    "Drop a bead on the string. What's the story right now?",
    "What's the main goal you're chasing this week?",
    "A quick snapshot of how life feels right now.",
    "Jot down the honest truth about how today is going.",
    "Got something to say? Get it down on paper.",
    "Just a quick check-in with yourself.",
  ],
};

export function getTimeBucket(hour: number): Exclude<TimeBucket, "anytime"> {
  if (hour >= 5 && hour < 9) return "earlyMorning";
  if (hour >= 9 && hour < 12) return "morning";
  if (hour >= 12 && hour < 17) return "afternoon";
  if (hour >= 17 && hour < 22) return "evening";
  return "night";
}

export function getTimelineSubtitle(date: Date = new Date(), location?: string): string {
  if (location && Math.random() < 0.15) {
    const locPrompts = [
      `Working or hanging out in ${location}.`,
      `A quick note from ${location}.`,
      `How's your time in ${location} going?`,
      `Capturing a moment from ${location}.`,
    ];
    return locPrompts[Math.floor(Math.random() * locPrompts.length)];
  }

  const hour = date.getHours();
  const bucket = getTimeBucket(hour);
  const pool = Math.random() < 0.2 ? PROMPT_CATALOG.anytime : PROMPT_CATALOG[bucket];
  const index = Math.floor(Math.random() * pool.length);
  return pool[index] ?? "Honestly, what's on your mind right now?";
}
